<link href="assets/admin/css/all/plugins/dataTables/select.bootstrap.min.css" rel="stylesheet">
<link href="assets/admin/css/all/plugins/jquery-treegrid/css/jquery.treegrid.css" rel="stylesheet"> <!--jquery.treegrid-->
<link href="assets/admin/css/bootstrap-colorpicker.min.css" rel="stylesheet"> <!--bootstrap.colorpicker-->

<script src="assets/admin/js/jquery-2.1.1.min.js"></script>
<script src="assets/admin/js/jquery-ui-1.10.4.min.js"></script>
<script src="assets/admin/js/datatables.min.js"></script>
<script src="assets/admin/js/all.min.js"></script>
<script>window.addEventListener("beforeunload",function(a){$.blockUI({css:{border:"none",padding:"15px",backgroundColor:"#000","-webkit-border-radius":"10px","-moz-border-radius":"10px",opacity:0.5,color:"#fff"}})});</script>
<script>$(document).on("click",".add_new",function(c){var a=[];$.each($("input[name='xmail[]']"),function(){a.push($(this).val())});c.preventDefault();var b=$(this).parent().parent().clone();b.appendTo(".destination")});$(document).on("click",".remove_one",function(b){b.preventDefault();var a=$(".copysection").size()-1;if(a){if(confirm("您確定要刪除所選取的項目嗎")){$(this).closest(".copysection").remove()}}});</script>
<script src="assets/ckeditor/ckeditor.js"></script>
<script src="assets/ckfinder/ckfinder.js"></script>
<script>
  synchronousMenu();
  function synchronousMenu(){var preid="<?=$this->session->preid?>";var preMenuID="<?=$this->session->preMenuID?>";var href="";var url="";url=location.href;var ifindex=url.indexOf("<?=$this->defaultURL?>");if(preid!=0&&preMenuID&&ifindex<=0){href="<?=(isset($this->mainurlPath))?$this->mainurlPath.'/index/'.$this->session->preid:$this->indexPath.'/index/'.$this->session->preid?>";$(".nav.metismenu a[href$='"+href+"']").parents("li").addClass("active");$(".nav.metismenu a[href$='"+href+"']").parents("ul.collapse").addClass("in");var element=$("ul.nav.metismenu a").filter(function(){return this.href.indexOf(href)>-1});if(element.length>0){var em2=element.filter(function(){return this.href=="<?=base_url()?>"+href});em2.attr("onclick","javascript:void(0)");em2.parent("li").addClass("nowopen")}else{element.attr("onclick","javascript:void(0)");element.parent("li").addClass("nowopen")}}else{href="<?=$this->session->nowurl?>";var em=$(".nav.metismenu a").filter(function(){return this.href.indexOf(href)>-1});if(em.length>1){if(ifindex>-1){em.eq(0).parents("li").addClass("active");em.eq(0).parent("li").addClass("nowopen")}else{$(".nav.metismenu a[href$='"+href+"']").parents("li").addClass("active")}}else{em.parents("li").addClass("active");em.parent("li").addClass("nowopen")}if(preMenuID){url=window.location;var element=$("ul.nav.metismenu a").filter(function(){return this.href==url||this.href.indexOf(href)>-1});if(element.length>0){element.eq(0).attr("onclick","javascript:void(0)");element.eq(0).parent("li").addClass("nowopen")}else{element.attr("onclick","javascript:void(0)")}}}};
  function recordurl(a,b,c,d){$.post("<?php echo site_url('common/administer/currenturl'); ?>",{id:a,url:b,name:c,custom:d},function(a){redirect(a)})};
  function ckfinderversion(a){var b="<?=$this->config->item('ckfinder_version')?>"; 2==b?CKFinder.setupCKEditor(a,"../","Files"):CKFinder.setupCKEditor(a,{resourceType:"Files"})};
  function BrowseServer(b){var a=new CKFinder;a.basePath="../";a.selectActionData=b;a.selectActionFunction=SetFileField;a.resourceType="Images";a.popup(800,480)};
  function SetFileField(c,a,d){var e="",b="",h="";a=a.selectActionData?a.selectActionData.split(","):[];0<a.length&&(e=a[0]);1<a.length&&(b=a[1]);2<a.length&&(h=a[2]);a=$('input[name="'+e+'"]');if("multi"==b)c="\u5df2\u9078\u64c7\u6a94\u6848";else{if(1<d.length){alert("\u4e0d\u53ef\u9078\u64c7\u591a\u500b\u6a94\u6848");return}b="";c&&(b=c.split("/"));c=0<b.length?b[b.length-1]:c}for(var f=[],g=0;g<d.length;g++){var k=d[g].url;b=k.split(".");1==validtype(e,b[1],h)&&f.push(k)}0<f.length&&a.next().html(c);
a.val(f);a.trigger("change")};
  function generateCkfinder(d,g,e){e=e||"";CKFinder.popup({resourceType:"Images",chooseFiles:!0,width:800,height:600,onInit:function(a){a.on("files:choose",function(b){var a=$('input[name="'+d+'"]');b=b.data.files;var c="";if("multi"==g)c="\u5df2\u9078\u64c7\u6a94\u6848";else{if(1<b.length){alert("\u4e0d\u53ef\u9078\u64c7\u591a\u500b\u6a94\u6848");return}c=b.first().get("name")}var f=[];b.forEach(function(a,b){var c=a.getUrl().split(".")[1];1==validtype(d,c,e)&&f.push(a.getUrl())});0<f.length&&a.next().html(c);
a.val(f);a.trigger("change")});a.on("file:choose:resizedImage",function(a){var b=a.data.resizedUrl,c=$('input[name="'+d+'"]');c.next().html(a.data.file.get("name"));c.val(b)});a.fire("files")&&(a=$('input[name="'+d+'"]'),a.next().html("<?=$this->filemsg?>"),a.val(""))}})};
  function BrowseServerAlbum(d){var a=new CKFinder;a.basePath="../";a.selectActionData=d;a.selectActionFunction=SetAlbumFileField;a.resourceType="Images";a.popup(800,480)}
  function SetAlbumFileField(d,a,e){var b="",c="",f="";a=a.selectActionData?a.selectActionData.split(","):[];0<a.length&&(b=a[0]);1<a.length&&(c=a[1]);2<a.length&&(f=a[2]);$('input[name="'+b+'"]');if("multi"!=c){if(1<e.length)return alert("\u4e0d\u53ef\u9078\u64c7\u591a\u500b\u6a94\u6848"),!1;c="";d&&(c=d.split("/"))}for(d=0;d<e.length;d++)a=e[d].url,c=a.split("."),1==validtype(b,c[1],f)&&(c=a,a=a.split("/"),$.post('<?=site_url($this->indexPath."/save/".NULL);?>',{xtitle:a[a.length-1],xfile1:c},function(a){if(a.error)return alert(a.error),!1}));location.reload()}
  function generateAlbumCkfinder(d,a,e){e=e||"";CKFinder.popup({resourceType:"Images",chooseFiles:!0,width:800,height:600,onInit:function(b){b.on("files:choose",function(c){$('input[name="'+d+'"]');c=c.data.files;if("multi"!=a){if(1<c.length)return alert("\u4e0d\u53ef\u9078\u64c7\u591a\u500b\u6a94\u6848"),!1;c.first().get("name")}c.forEach(function(a,c){var b=a.getUrl().split(".")[1];if(1==validtype(d,b,e)){var b=a.getUrl(),f=a.get("name");$.post('<?=site_url($this->indexPath."/save/".NULL);?>',{xtitle:f,xfile1:b},function(a){if(a.error)return alert(a.error),!1})}});location.reload()});b.on("file:choose:resizedImage",function(a){var c=a.data.resizedUrl,b=$('input[name="'+d+'"]');b.next().html(a.data.file.get("name"));b.val(c)});b.fire("files")&&(b=$('input[name="'+d+'"]'),b.next().html("<?=$this->filemsg?>"),b.val(""))}})};
  function getHWarray(d,b){var c;$.ajax({url:"common/administer/getImageLimit/<?=$this->table?>/"+d+"/"+(b||""),async:!1,success:function(a){c=a}});return c}
  function validtype(a,c,d){var b="";$.ajax({url:"common/administer/checkImagetype/<?=$this->table?>/"+a+"/"+c+"/"+(d||""),async:!1,success:function(a){b=a}});return b};
  function initTableOption(g){var h=parseInt("<?php if(isset($this->currentPage)) echo $this->currentPage; ?>"),a=parseInt("<?php if(isset($this->pageSize)) echo $this->pageSize; ?>"),b=[10,25,50,75,100],c=[];if(-1==b.indexOf(a))for(var e=0,f=0,d=0;d<b.length;d++)b[d]>a&&0==f&&(f++,c[e]=a),c[e+f]=b[d],e++;else c=b;return options={language:{emptyTable:"\u5c1a\u672a\u6709\u4efb\u4f55\u8cc7\u6599",infoEmpty:"\u7e3d\u5171 0 \u7b46",lengthMenu:"\u6bcf\u9801\u986f\u793a _MENU_ \u7b46",search:"\u641c\u5c0b\u5168\u90e8\u6b04\u4f4d:",paginate:{first:"\u7b2c\u4e00\u9801",previous:"\u4e0a\u4e00\u9801",next:"\u4e0b\u4e00\u9801",last:"\u6700\u5f8c\u4e00\u9801"}},info:!1,paging:"<?=$this->showPaging?>",searching:"<?=$this->showSearching?>",lengthChange:!0,lengthMenu:c,pageLength:a,processing:!0,ajax:{url:g},order:[],columnDefs:[],createdRow:function(a,b,c){$(a).addClass("gradeX");$(a).attr("data-id",b.pid)},pagingType:"simple_numbers",displayStart:(h-1)*a,autoWidth:!1}};
  $.fn.dataTable.ext.order["dom-text"]=function(b,a){return this.api().column(a,{order:"index"}).nodes().map(function(d,c){return $("input",d).val()})};
  function batchItem(b){var a=[];$.each($("input[name='checkbox[]']:checked"),function(){a.push($(this).val())});if(a.length==0){alert("請選擇項目");return false}if(confirm("確定執行?")){$.post("<?php echo site_url($this->indexPath.'/batchItem'); ?>/"+b,{data:a},function(c){if(c.error){alert(c.error)}if(c.success){location.reload()}})}}function sort(a){var b=$(".dataTables-example").DataTable().page.info().start;$.post("<?php echo site_url($this->indexPath.'/sort'); ?>",{data:a,start:b},function(c){})};
  function readSort(e,b,d){e=e||0;b=b||"xtitle";d=d||false;if($.fn.dataTable.isDataTable(".sortDataTables")){c=$(".sortDataTables").DataTable()}else{if(d==true){var a="<?php echo site_url($this->indexPath.'/read');?>/"+e+"/<?=$this->session->userdata('preid')?>"}else{var a="<?php echo site_url($this->indexPath.'/read');?>/"+e}var c=$(".sortDataTables").DataTable({language:{emptyTable:"尚未有任何資料",infoEmpty:"總共 0 筆",lengthMenu:"每頁顯示 _MENU_ 筆",search:"搜尋全部欄位:",paginate:{first:"第一頁",previous:"上一頁",next:"下一頁",last:"最後一頁",}},info:false,processing:true,ajax:{url:a,},columns:[{data:b},],select:{style:"single"},order:[],})}c.on("select",function(j,h,g,f){var i=c.rows(f).data().toArray();$("input[name='insertxsortpid']").val(i[0]["pid"])}).on("deselect",function(i,h,g,f){$("input[name='insertxsortpid']").val("")})}function deleteFile(b,a){if(confirm("確定刪除")){$.post("<?php echo site_url($this->indexPath.'/saveFile');?>",{id:b,field:a},function(c){alert("刪除成功");redirect(document.referrer)})}}var action="<?=$action?>";if(action=="index"){listinit()}if(action!="index"){forminit();$('input:radio[name="xsort"]').on("change",function(){if(this.value=="insert"){$(".table-insert").show()}else{$(".table-insert").hide()}})};
  function handler(){return false;}
  if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) { $('table').removeClass('sorted_table');}
  function AutoUpdSeo(tb,input,output,isurl){if(tb&&input&&output&&isurl){$.post("common/administer/AutoUpdSeo"+"/"+tb,{input:input,output:output,isurl:isurl},function(data){alert("同步成功");location.reload()})}};
</script>
<script>window.chartColors={red:"rgb(255, 99, 132)",orange:"rgb(255, 159, 64)",yellow:"rgb(255, 205, 86)",green:"rgb(75, 192, 192)",blue:"rgb(54, 162, 235)",purple:"rgb(153, 102, 255)",grey:"rgb(231,233,237)"};</script>
<script>function changelang(f){var d="<?=$this->defaultURL?>?lang="+f;var b='<?=(isset($_GET["lang"]))?true:false?>';var c="<?=$this->searchlang?>";var a="<?=strpos(current_url(),'/form')?>";if(!b&&c){var e="/"+c+"/";var g=window.location.href.split(e);if(g.length>0&&a<=0){d=g[0]+"/"+f+"/"+g[1]}}redirect(d)};</script>
